# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trpc.proto\x12\x03rpc\"\x1f\n\x0f\x44ocumentRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\" \n\x10\x44ocumentResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\",\n\x0e\x44ocumentUpdate\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"&\n\x08\x44ocument\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t2\xeb\x01\n\tFirestore\x12\x35\n\x0b\x41\x64\x64\x44ocument\x12\r.rpc.Document\x1a\x15.rpc.DocumentResponse\"\x00\x12<\n\x0bGetDocument\x12\x14.rpc.DocumentRequest\x1a\x15.rpc.DocumentResponse\"\x00\x12\x33\n\x0eUpdateDocument\x12\x13.rpc.DocumentUpdate\x1a\n.rpc.Empty\"\x00\x12\x34\n\x0e\x44\x65leteDocument\x12\x14.rpc.DocumentRequest\x1a\n.rpc.Empty\"\x00\x42\x05Z\x03rpcb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\003rpc'
  _DOCUMENTREQUEST._serialized_start=18
  _DOCUMENTREQUEST._serialized_end=49
  _DOCUMENTRESPONSE._serialized_start=51
  _DOCUMENTRESPONSE._serialized_end=83
  _DOCUMENTUPDATE._serialized_start=85
  _DOCUMENTUPDATE._serialized_end=129
  _EMPTY._serialized_start=131
  _EMPTY._serialized_end=138
  _DOCUMENT._serialized_start=140
  _DOCUMENT._serialized_end=178
  _FIRESTORE._serialized_start=181
  _FIRESTORE._serialized_end=416
# @@protoc_insertion_point(module_scope)
